GET http://localhost:8000/api/actions

###

GET http://localhost:8000/api/actions/1

###

POST http://localhost:8000/api/actions
Content-Type: application/json

{
    "project_id": 2,
    "description": "Beat all bosses",
    "notes": "Even though I have beaten the final boss, there are still more bosses and areas to beat.",
    "completed": false
}